site_name: FakerPHP / Faker
site_description: Documentation for FakerPHP / Faker

repo_name: FakerPHP/Faker
repo_url: https://github.com/FakerPHP/Faker
edit_uri: https://github.com/FakerPHP/fakerphp.github.io/edit/main/docs/

theme:
  name: material
  font:
    text: 'Nunito'
    code: 'Fira Code'
  palette:
    scheme: default
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FakerPHP/Faker
      name: Faker repository
    - icon: fontawesome/regular/file-alt
      link: https://github.com/FakerPHP/fakerphp.github.io
  name: Docs repository

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.keys
